### ISSUE TITLE
workspace/project load times are undefined

### ISSUE THREAD

**Issue by johnmuhl** [atom/timecop#24]
~~~
# lsb-release -a
LSB Version:	core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:core-3.2-x86_64:core-4.0-x86_64:desktop-4.0-amd64:desktop-4.0-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch
Distributor ID:	openSUSE Tumbleweed
Description:	openSUSE Tumbleweed
Release:	20170213
Codename:	n/a

# uname -a
Linux machine 4.10.9-1-default #1 SMP PREEMPT Sat Apr 8 15:30:03 UTC 2017 (195f937) x86_64 x86_64 x86_64 GNU/Linux

# atom -v
Atom    : 1.17.0-beta3
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0
~~~

Running `atom --safe` and checking timecop shows:

![screenshot from 2017-04-22 09-58-14](https://cloud.githubusercontent.com/assets/7944/25305556/f76766ba-2742-11e7-9a04-dfdb18a0e2e6.png)

Can only reproduce when Atom starts with no projects.

**Comment by khaister** [comment]
If there is no project folder included, workspace and project load times are null, hence 'undefinedms'. I've made a change to show these as 'NA' instead, reasoning that it might be more helpful than 'undefinedms'. Created a pull request.

**Comment by rsese** [comment]
I can reproduce this in 1.16.0  on macOS 10.12.4 as well but only when starting with no project like @khaister mentioned (updated the issue body to mention this).  Thanks for the report @johnmuhl and thanks for opening a PR @khaister :v:

**Comment by khaister** [comment]
Are there any plans to fix this issue? I think I closed the PR by mistake but I can reopen it if needed.

Also, I was thinking maybe we can show `-` instead of `NA` for undefined load times.

**Comment by 50Wliu** [comment]
Looks like this also happens when loading a project for the first time, because there is no state to deserialize.
